# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

parameters:
- name: client
  displayName: Hosted Client Name
  type: string
  default: HOSTING_Prod
  values:
  - HOSTING_Prod
  - GILEAD_Test
  - FREDDIEMAC_Dev
  - HYUNDAI_Dev
  - INDEED_Dev
  - INTEL_Dev
  - ROCKWELL_TEST
  
pool: Teamconnect_Sandbox
  
  
steps:

- template: send-email.yml
  parameters:
    client: ${{ parameters.client }}
- template: suppress-appdynamics.yml
  parameters:
    client: ${{ parameters.client }}
- template: suppress-statuscake.yml
  parameters:
    client: ${{ parameters.client }}
#- template: shutdown-application.yml
#  parameters:
#    client: ${{ parameters.client }}
- template: delete-cache.yml
  parameters:
    client: ${{ parameters.client }}
#- template: start-application.yml
#  parameters:
#    client: ${{ parameters.client }}
- template: url-check.yml
  parameters:
    client: ${{ parameters.client }}
- template: complete-email.yml
  parameters:
    client: ${{ parameters.client }}
    
    
    


