# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

name: ${{ parameters.client }}_Restart$(Rev:.rr)
parameters:
- name: Salesforce
  type: string
  default: 123456
- name: email
  type: string
  default: sunny.kathuria@mitratech.com
- name: client
  displayName: Hosted Client Name
  type: string
  default: MAESTRO_Test
  values:
  - ALIGHTSOLUTIONS_Dev
  - ALIGHTSOLUTIONS_Test
  - AMGEN_Test
  - AMGEN_Dev
  - ALLY_Dev
  - AMNEAL_Test
  - AMTRUSTFINANCIAL_Dev
  - AMTRUSTFINANCIAL_Test
  - BNSF_Test
  - BRUNSWICK_Dev
  - BRUNSWICK_Test
  - CANADIANIMPBANK_Dev
  - CANADIANIMPBANK_Test
  - CARRIER_Dev
  - CASTLETON_Dev
  - COLLABORATI_Stage
  - CSAA_Dev
  - CSAA_Test
  - EMP_Test
  - EVERGREEN_Dev
  - FIDELITY_Dev
  - FIDELITY_Test
  - FIDELITY_Uat
  - FINRA_Dev
  - FINRA_Test
  - FREDDIEMAC_Dev
  - GILEAD_Dev
  - GILEAD_Test
  - HOMEDEPOT_Test
  - HOSTING_Prod
  - HYUNDAI_Dev
  - HYUNDAI_Test
  - INDEED_Dev
  - INTEL_Dev
  - INTEL_Test
  - INTLAUTOCOMPGRPNA_DEV
  - JAZZPHARMA_Dev
  - JMFAMILY_Test
  - LIBERTYMUTUAL_Dev
  - LIBERTYMUTUAL_TEMP1
  - LIBERTYMUTUAL_TEST
  - MAESTRO_Test
  - MARRIOTT_Dev
  - MARRIOTT_Test
  - MICRON_Dev
  - MICRON_Test
  - MORGANSTANLEY_Dev
  - MORGANSTANLEY_Test
  - NASHVILLEAIRPORT_Dev
  - NAVISTAR_Dev
  - NETAPP_Dev
  - NETAPP_Test
  - NFL_Test
  - OCCIDENTALPETRO_Dev
  - OCCIDENTALPETRO_Test
  - PGECORP_Test
  - PROGRESSIVE_Dev
  - PRUDENTIAL_Dev
  - PRUDENTIAL_Uat
  - PURDUEPHARMA_Dev
  - PURDUEPHARMA_Test
  - RECKITTBENCKISER_Test
  - ROCKWELL_Dev
  - ROCKWELL_TEST
  - SAINTGOBAIN_DEV
  - SEALEDAIR_DEV
  - SELECTIVE_Dev
  - SELECTIVE_Test
  - SEMPRA_TEST
  - SEVENTYSEVEN_Test
  - SLALOM_Dev
  - SOUTHWEST_DEV
  - SOUTHWEST_TEST2
  - TEVAPHARM_Dev
  - TEVAPHARM_TEST
  - TORONTODOMINION_DEV
  - TRANETECHNOLOGIES_DEV
  - TRANETECHNOLOGIES_Test
  - TROWEPRICE_DEV
  - TROWEPRICE_TEST
  - UNIVOFCOLORADO_DEV
  - VIACOM_DEV
  - VIACOM_TEST
  - WEWORK_DEV
  - WHIRLPOOL_Dev
  - WHIRLPOOL_Test
  - WILLISGRPSERVICES_TEST
  - WPX_Test
  - XCELENERGY_Dev
  - XCELENERGY_Test
  - XEROX_DEV
  - XEROX_TEST
  - ZURICH_TEST
  
pool: Teamconnect_Sandbox
  
  
stages:
- stage: Application_Restart
  displayName: Application_Restart
  jobs:
  - job: Application_Restart
    pool:
      name: Teamconnect_Sandbox
    
    
    steps:

      - script: echo ${{ parameters.client }} Application will be starting
      
          
   
- stage: ${{ parameters.client }}
  displayName: ${{ parameters.client }}
  jobs:
  #- job: ${{ parameters.client }}
  - deployment: ${{ parameters.client }}
    displayName: ${{ parameters.client }}
    pool:
      name: Teamconnect_Sandbox
              
    steps:
       - template: send-email.yml
          parameters:
            client: ${{ parameters.client }}
            email: ${{ parameters.email }}
       - template: suppress-appdynamics.yml
         parameters:
           client: ${{ parameters.client }}
       - template: suppress-statuscake.yml
         parameters:
           client: ${{ parameters.client }}
      - template: shutdown-application.yml
        parameters:
           client: ${{ parameters.client }}
      - template: delete-cache.yml
        parameters:
          client: ${{ parameters.client }}
      - template: start-application.yml
        parameters:
          client: ${{ parameters.client }}
      - template: url-check.yml
        parameters:
          client: ${{ parameters.client }}
      - template: complete-email.yml
        parameters:
          client: ${{ parameters.client }}
          email: ${{ parameters.email }}
          
- stage: Salesforce_${{ parameters.Salesforce }}
  displayName: Salesforce_${{ parameters.Salesforce }}
  jobs:
  - job: Salesforce_${{ parameters.Salesforce }}
    pool:
      name: Teamconnect_Sandbox
      
    steps:
      - script: echo ${{ parameters.Salesforce }}

          


    
    


