# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
- name: client
  displayName: Hosted Client Name
  type: string
  default: HOSTING_Prod
  values:
  - HOSTING_Prod
  - GILEAD_Test
  - FREDDIEMAC_Dev
  - HYUNDAI_Dev
  - INDEED_Dev
  - INTEL_Dev
  
steps:
  - script: cat /opt/oracle/notification_start.out | mail -s "TeamConnect $ManagedServerName Restart Notice " -S from=no-reply@mitratech.com sunny.kathuria@mitratech.com
   
    displayName: 'Send Starting Email'
    env:
      ManagedServerName: ${{ parameters.client }}
